# Generated by Django 3.1.3 on 2020-11-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Associations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('association_name', models.CharField(max_length=100)),
                ('incharge', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=500)),
                ('contacts', models.CharField(max_length=300)),
            ],
        ),
    ]
