# Generated by Django 3.1.2 on 2020-10-25 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='content',
        ),
        migrations.CreateModel(
            name='ReadingVerse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField()),
                ('start_verse', models.IntegerField()),
                ('end_verse', models.IntegerField()),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.reading')),
            ],
        ),
    ]
